language: generic
sudo: required
services:
- docker
before_script:
- scripts/docker-build
script:
- docker run -e BROWSER_STACK_USERNAME=${BROWSER_STACK_USERNAME} -e BROWSER_STACK_ACCESS_KEY=${BROWSER_STACK_ACCESS_KEY}
  bulbs-elements scripts/ci
env:
  global:
  - secure: zrbG1OpK+wApDnHDy2awhP3EElC6Coyw4uw9Im84YDQCi2eov+ALiU5OeDrhlp8DqDCKIa1G8F8YmdsBbbFuxFjC8pZZHrKy3bgNe3WYdiiT34rxG2gXcnr8XQERQf0KOnpbChQA7QgFcEXSP4ChvqCtMtRn04RCBY3+bCwwCNumTnSvoh/SSmuI1aA0wTDuSAYz27wpKAAnj7Og+tKq7ihYSjSpJC/ePRL8nUTUGzLLFVFHervTXu3zM7L2SRKZR3TyFP/lXeoNrYSRK1HO90niXihy6gUcFvTYuxJGxHtoGaw97E4zuOsujrT6El82urhn5HlLTALux4MzUUjHbWNn1aDgPlcmgqsnD78M/+d6EBYxL18Z7PdVFoyJqD9xXKX+31jnGHydL7oRhk22ULiFJF0aXkiA1ho5Owp7OfXNLGyjPN9wjrrwFTvSj65OaMRuUWJ6Tug5WKfWThtHYN0TEAeRUof08OYjJvqeAZIvm6fmmnIUc5m1ouBlv+XdFeGtksU5HM0kemQD+FkvqHMFB2ug/uABf2t/8zJMrTbhE70Vo0vKnXleE3iAzxj3Gplc/ctwauSMatQx3SGL3bX7jmI/NvrL6Wp/H1U9hyr65fclvxbrz4htp5C8z/sSFpYHQqf0WtFZgtIxlhbXfpaixAfciMjaGcD+a8l6BlA=
  - secure: axsQaV4bTr5+F9B31AtFRhFcybHx8VpOK8ld45Nj5AuQhFIwqKTi5edwrpmlRXqISQHa6xvyxzm55VupJ6GODDMR44s8xzGkVEtQ59yIzOdCR3hFlSTcJaKjg4VU+l8I3pjSoXTchCn9wTENoD5NTqznku3p2mZo7Mov2/y5OCIyBGqW5dAuEl4cF9Oe2j4Bsu3p5IFv6MRarhg44kfRhHRxvcF4eO3UzvIwhkA/eAog4U5GpsvSa/D+lLVvvM2zqHy0qIDhemBTw4kb/aL1MPZW/Ud0yN8pxeNiAFUBAe7rb3xKX3O702itwkdZUBnxg6F0M5fLq9A8lwigcQyljh9RvbMDRiOxGYBa5gC0GTRtyGvCGZAwQLC27fEiIIBFMH1U35bICtJo2tznFGi7BnWNAaHVhfsyrDoPU8cOVvoryvZMZccpE1mpE3NVdqH6oZILDZ0qr+gBGgjv2BZIKYTmC5/uT10abDVwr8lC2FkqDlwK0ueISvNbDekm9ei1kaJ6WWlCV7a7OzUCxaZvo3OHRXQba2GurA26o2ljW+Gm4TQG42TIKZMakdytRbPH0y7Ff6Cb3/JipQm/QD19RPWi8c2teM1YxrUk2/eAbJxQ0LBl04xVWv3By8SKse4k0nFyDlmCK+1KcbWs4ilZAwGFIYkSWJHmQzgcJHurYt8=
