#!/usr/bin/env bash
set -e

# mparent(2018-03-28): Browserstack account cancelled (Bulbs deprecated).
# # List of browsers to test
# BROWSERS=(
#     bs_safari_9
#     bs_ie_11
#     bs_firefox_47
#     bs_chrome_50
# )

# for B in ${BROWSERS[@]}; do
#     BROWSER=$B ./node_modules/.bin/karma start karma.devicelab.js --single-run
# done

# Lint
npm run lint
