#!/usr/bin/env bash

# mparent(2016-09-12): Temp Travis/Docker Testing
export CHROME_BIN=chromium-browser
export DISPLAY=:99.0
sh -e /etc/init.d/xvfb start

./node_modules/.bin/karma start karma.devicelab.js --single-run
