#!/usr/bin/env node
var Van = require("van")

var van = new Van({
  scripts: {
    webpack: 'node_modules/.bin/webpack --watch', 
    karma: 'node_modules/.bin/karma start',
  }
});

// spawn the child processes and interleave output 
van.start();

process.on('SIGINT', function() {
  // send a kill signal to each child process 
  van.stop();
});
