#!/usr/bin/env bash
set -e

# This script:
# * moves dist/ to .dist/
# * checks out HEAD as a detached head
# * runs a production build
# * creates a git tag named TAG
# * pushes that tag to github
# * checks out the branch you started on
# * deletes dist/
# * restores .dist/ to dist/

function secho {
  echo "$LOG_PREFIX $1"
}

secho "Starting release process..."
BRANCH_NAME_RELEASE="master"
BRANCH_NAME="$(git symbolic-ref --short HEAD)"
if [ "$BRANCH_NAME" = "$BRANCH_NAME_RELEASE" ]; then
  secho "On releasable branch '$BRANCH_NAME_RELEASE'"
else
  secho "You are currently on branch '$BRANCH_NAME', please switch to '$BRANCH_NAME_RELEASE' before running this command, exiting..."
  exit 1
fi

mv dist/ .dist/ || true

function  cleanup_at_exit {
  secho "Resetting local checkout"
  git checkout - --quiet
  rm -rf dist/ || true
  mv .dist/ dist/ || true
}
trap cleanup_at_exit EXIT

LOG_PREFIX="[RELEASE] [$(date)]"

TAG=$(cat package.json \
  | grep version \
  | head -1 \
  | awk -F: '{ print $2 }' \
  | sed 's/[",]//g' \
  | tr -d '[[:space:]]')

secho "Checking out detached HEAD"
git checkout $(git rev-parse HEAD) --quiet

secho "Running scripts/webpack-prod-build"
scripts/webpack-prod-build

secho "Adding dist to detached HEAD"
git add -f 'dist/*'

secho "Tagging and Releasing"
git commit --allow-empty --quiet -m "production build for release tag: $TAG"
git tag $TAG
git push origin $TAG

node_modules/.bin/onionsay "NEW VERSION: $TAG"

