#!/usr/bin/env bash
set -e

# This script:
# * moves dist/ to .dist/
# * moves .test/ to .test-tmp/
# * runs a devicelab build
# * runs devicelab tests
# * deletes dist/
# * restores .dist/ to dist/
# * deletes .test/
# * restores .test-tmp/ to .test/

mv dist/ .dist/ || true
mv .test/ .test-tmp/ || true

function  cleanup_at_exit {
  rm -rf dist/ || true
  mv .dist/ dist/ || true
  rm -rf .test/ || true
  mv .test-tmp/ .test || true
}
trap cleanup_at_exit EXIT

scripts/webpack-devicelab-build

node_modules/.bin/karma start karma.devicelab.js --single-run
