#!/usr/bin/env bash
export NODE_ENV=production
set -e
node_modules/.bin/webpack \
  --bail \
  --color \
  --devtool source-map \
  --progress \
  --config webpack.config.prod.js \
  --json \
  > stats.json

echo 'Upload ./stats.json at: http://webpack.github.io/analyse/'
